version: '3.4'

# This override file should be used in development environments to
# connect this service to sibling services from other repositories

services:
  mine-support-calculation-service:
    command: >
      sh -c "
        scripts/wait-for/wait-for mine-support-message-queue:5672 --
        npm run start:watch"
    networks:
      - mine-support
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

networks:
  mine-support:
    external: true

volumes:
  node_modules: {}
