version: '3.4'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  mine-support-calculation-service:
    command: >
      sh -c "
        scripts/wait-for/wait-for mine-support-calculation-message-queue:5672 --
        npm run test"
    volumes:
      - ./test-output:/usr/src/app/test-output

volumes:
  node_modules: {}
