version: '3.7'
services:
  ffc-demo-calculation-service:
    build:
      context: .
      target: production
    image: ffc-demo-calculation-service
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-demo-calculation-service-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      CALCULATION_QUEUE_ADDRESS: ${CALCULATION_QUEUE_ADDRESS}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      PAYMENT_QUEUE_ADDRESS: ${PAYMENT_QUEUE_ADDRESS}
