apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        environment: {{ .Values.environment }}
      annotations:
        redeployOnChange: {{ .Values.container.redeployOnChange | quote }}
    spec:
      restartPolicy: {{ .Values.container.restartPolicy }}
      containers:   
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        {{- if .Values.container.command }}
        {{- with .Values.container.command }}
          command:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.container.args }}
          args:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        securityContext:
          runAsUser: {{ .Values.container.runAsUser }}
          runAsNonRoot: {{ .Values.container.runAsNonRoot }}
          readOnlyRootFilesystem: {{ .Values.container.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.container.allowPrivilegeEscalation }}
        env:                
        - name: NODE_ENV
          value: {{ .Values.environment }}
        - name: MESSAGE_QUEUE_HOST
          value: {{ .Values.container.messageQueueHost }}
        - name: MESSAGE_QUEUE_PORT
          value: {{ .Values.container.messageQueuePort | quote }}
        - name: MESSAGE_QUEUE_TRANSPORT
          value: {{ .Values.container.messageQueueTransport }}
        - name: CALCULATION_QUEUE_ADDRESS
          value: {{ .Values.container.calculationQueueAddress }}
        - name: CALCULATION_QUEUE_USER
          value: {{ .Values.container.calculationQueueUser }}
        - name: CALCULATION_QUEUE_PASSWORD
          value: {{ .Values.container.calculationQueuePassword }}
        - name: PAYMENT_QUEUE_ADDRESS
          value: {{ .Values.container.paymentQueueAddress }}
        - name: PAYMENT_QUEUE_USER
          value: {{ .Values.container.paymentQueueUser }}
        - name: PAYMENT_QUEUE_PASSWORD
          value: {{ .Values.container.paymentQueuePassword }}
        resources:
          requests:
            memory: {{ .Values.container.requestMemory }}
            cpu: {{ .Values.container.requestCpu }}
          limits:
            memory: {{ .Values.container.limitMemory }}
            cpu: {{ .Values.container.limitCpu }}   
