{{- include "ffc-helm-library.container-config-map" (list . "ffc-demo-calculation-service.config-map") -}}
{{- define "ffc-demo-calculation-service.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  MESSAGE_QUEUE_PORT: {{ quote .Values.container.messageQueuePort }}
  MESSAGE_QUEUE_TRANSPORT: {{ quote .Values.container.messageQueueTransport }}
  CALCULATION_QUEUE_ADDRESS: {{ quote .Values.container.calculationQueueAddress }}
  PAYMENT_QUEUE_ADDRESS: {{ quote .Values.container.paymentQueueAddress }}
{{- end -}}