{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-calculation-service.container-secret") -}}
{{- define "ffc-demo-calculation-service.container-secret" -}}
stringData:
  CALCULATION_QUEUE_USER: {{ quote .Values.container.calculationQueueUser }}
  CALCULATION_QUEUE_PASSWORD: {{ .Values.container.calculationQueuePassword | quote }}
  PAYMENT_QUEUE_USER: {{ quote .Values.container.paymentQueueUser }}
  PAYMENT_QUEUE_PASSWORD: {{ .Values.container.paymentQueuePassword | quote }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
{{- end -}}
